### ISSUE TITLE
BUG: Tab display is erratic - again

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/sfb1451-projects-catalog#28]
This has been an issue for a long time, and we have iterated between several different options, sometimes even reverting. The current problem is related to javascript code when loading a dataste page:

```
vue.2.6.14.min.js:6 TypeError: Cannot read properties of undefined (reading '$children')
    at a.setCorrectTab (app_component_dataset.js:492:46)
    at a.created (app_component_dataset.js:720:16)
```

The `this.$refs` references seem to be undefined in the `created()` and `mounted()` functions. The current functionality was introduced in order to allow dynamic switching of active tabs based on the tab content (e.g. switch to the 2nd tab if the first tab does not have content). This came after many iterations, with related issues:

- https://github.com/datalad/datalad-catalog/issues/300
- https://github.com/datalad/datalad-catalog/issues/268
- https://github.com/datalad/datalad-catalog/issues/266

I believe the best for UX (and to circumvent the error) would be to always display the first tab (subdatasets) even if it does not have any.

**Comment by jsheunis** [comment]
Another current issue is that the tab display does not work as currently intended, sometimes it switched to e.g. tab 3, even if tab 2 has content.

**Comment by jsheunis** [comment]
addressed in https://github.com/datalad/datalad-catalog/pull/350
